### List games
GET http://localhost:3333/games

### Get game by Id
GET http://localhost:3333/games/18122

### List ads
GET http://localhost:3333/ads

### Create Ad
POST http://localhost:3333/games/18122/ads
Content-Type: application/json

{
  "name": "WolfDolf",
  "yearsPlaying": 1,
  "discord": "Rodolfo H Okino#5186",
  "weekDays": [0,5,6],
  "hourStart": "21:00",
  "hourEnd" : "23:30",
  "useVoiceChannel": false
}

### List ads by gameId
GET http://localhost:3333/games/18122/ads

### Get discord by adId
GET http://localhost:3333/ads/7485ce83-1fc6-4c10-85fb-91a615e158ca/discord
