### List games
GET http://localhost:3333/games

### Get game by Id
GET http://localhost:3333/games/18122

### List ads
GET http://localhost:3333/ads

### Create Ad
POST http://localhost:3333/games/516575/ads
Content-Type: application/json

{
  "name": "DiegoWW",
  "yearsPlaying": 2,
  "discord": "Diego Fernandes#1234",
  "weekDays": [0,5,6],
  "hourStart": "19:00",
  "hourEnd" : "22:30",
  "useVoiceChannel": true
}

### Create Ad with errors
POST http://localhost:3333/games/21779/ads
Content-Type: application/json

{
  "name": "D",
  "yearsPlaying": 2.5,
  "discord": "#1234",
  "weekDays": [-1,"5",7],
  "hourStart": "9:00",
  "hourEnd" : "",
  "useVoiceChannel": "true"
}

### List ads by gameId
GET http://localhost:3333/games/18122/ads

### Get discord by adId
GET http://localhost:3333/ads/7485ce83-1fc6-4c10-85fb-91a615e158ca/discord
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsiUkVBRCIsIldSSVRFIl0sImlhdCI6MTY2Mzk4MTQ0NCwiZXhwIjoxNjY0MDY3ODQ0LCJzdWIiOiI3Mzc3ODA0OTM5NjUzMjgzODQifQ.50ISO3h-G1mGsDZABeXRiX0OSOH-yMuwd3pGytoxH6c


### Authenticate user
POST http://localhost:3333/oauth/login
Content-Type: application/json

{
  "code": "PFsu6j22pmbCPBWEivFLcXOGeHaouz"
}

### Get auth user infos
GET http://localhost:3333/oauth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsiUkVBRCIsIldSSVRFIl0sImlhdCI6MTY2Mzk4MTQ0NCwiZXhwIjoxNjY0MDY3ODQ0LCJzdWIiOiI3Mzc3ODA0OTM5NjUzMjgzODQifQ.50ISO3h-G1mGsDZABeXRiX0OSOH-yMuwd3pGytoxH6c
